name: Quality and Release

on:
  push:
    branches:
      - main

jobs:
  quality-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run quality tests
        run: pnpm quality

  version-or-publish-packages:
    runs-on: ubuntu-latest
    needs: quality-tests
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install
        with:
          command: pnpm install --no-frozen-lockfile

      - name: Create PR or Publish Package
        uses: changesets/action@v1
        with:
          version: pnpm version:stable
          publish: pnpm release:stable
          commit: "🤖 ci(changesets): version packages"
          title: "🤖 ci(changesets): version packages"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
