name: Merge to main

on:
  push:
    branches:
      - main

jobs:
  prerelease-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run prerelease tests
        run: pnpm prerelease

  version-or-publish-packages:
    runs-on: ubuntu-latest
    needs: prerelease-tests
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Create PR or Publish Package
        uses: changesets/action@v1
        with:
          version: pnpm version:stable
          publish: pnpm release:stable
          commit: 'chore(release): publish packages'
          title: 'chore(release): publish packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
